### ISSUE TITLE
[Error] V17 - linux AMD 64 - Make error disc.c  [-Wincompatible-pointer-types]

### ISSUE THREAD

**Issue by Hechelion** [sarah-walker-pcem/pcem#321]
**Describe the bug**
When I run the "make" command, I get the following error:

> 
> gcc -DPACKAGE_NAME=\"PCem\" -DPACKAGE_TARNAME=\"pcem\" -DPACKAGE_VERSION=\"v17\" -DPACKAGE_STRING=\"PCem\ v17\" -DPACKAGE_BUGREPORT=\"Sarah\ Walker\ \<pcem@pcem-emulator.co.uk\>\" -DPACKAGE_URL=\"\" -DPACKAGE=\"pcem\" -DVERSION=\"v17\" -DHAVE_LIBPTHREAD=1 -DHAVE_LIBGL=1 -DHAVE_LIBOPENAL=1 -I.    -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.2 -I/usr/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -I/usr/include/SDL2 -D_REENTRANT     -O3 -fcommon -MT pcem-disc.o -MD -MP -MF .deps/pcem-disc.Tpo -c -o pcem-disc.o `test -f 'disc.c' || echo './'`disc.c
> disc.c: In function ‘disc_reset’:
> disc.c:209:37: error: passing argument 2 of ‘timer_add’ from incompatible pointer type [-Wincompatible-pointer-types]
>   209 |         timer_add(&disc_poll_timer, disc_poll, NULL, 0);
>       |                                     ^~~~~~~~~
>       |                                     |
>       |                                     void (*)(void)
> In file included from ibm.h:5,
>                  from disc.c:1:
> timer.h:47:42: note: expected ‘void (*)(void *)’ but argument is of type ‘void (*)(void)’
>    47 | void timer_add(pc_timer_t *timer, void (*callback)(void *p), void *p, int start_timer);
>       |                                   ~~~~~~~^~~~~~~~~~~~~~~~~~
> disc.c:135:6: note: ‘disc_poll’ declared here
>   135 | void disc_poll()
>       |      ^~~~~~~~~
> disc.c: In function ‘disc_stop’:
> disc.c:286:17: error: too many arguments to function ‘drives[drive].stop’; expected 0, have 1
>   286 |                 drives[drive].stop(drive);
>       |                 ^~~~~~             ~~~~~
> In file included from disc.c:4:
> disc.h:9:16: note: declared here
>     9 |         void (*stop)();
>       |                ^~~~
> make[1]: *** [Makefile:2183: pcem-disc.o] Error 1
> 

**To Reproduce**

Resolve the following dependencies:

- OpenAI (1:1.24.2-1)
- SDL2 (2.32.4+dfsg-1)
- wxWidgets (3.2.8+dfsg-2)

Run the installation instructions found in the INSTALL file:

> ./configure

> make

**Expected behavior**
The make command is not expected to generate any errors that terminate the compilation.

**Host machine**

- OS: Ubuntu 25.10
- Emulator: PCemV17Linux
- gcc (Ubuntu 15.2.0-4ubuntu4) 15.2.0

- KDE 6.4.5
- Kernal 6.17.0-8-generic (64-bit)
- CPU 16 × AMD Ryzen 9 6900HX with Radeon Graphics

**Additional context**
I'm working on a clean install of Ubuntu 25.10 installed from scratch this weekend.

I resolved the dependencies and the ./configure command does not return any errors.

> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... ./install-sh -c -d
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking for style of include used by make... GNU
> checking dependency style of gcc... gcc3
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... gcc3
> checking whether to build for release... no
> checking whether to enable debugging... no
> checking whether to enable networking... no
> checking whether to use ALSA for MIDI output... no
> checking for cpu... x86_64
> checking for off64_t x86_64... no
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for SDL... yes
> checking for wx-config... /usr/bin/wx-config
> checking for wxWidgets version >= 3.0.0... yes (version 3.2.8)
> checking for wxWidgets static library... no
> checking for pthread_create in -lpthread... yes
> checking for glGetError in -lGL... yes
> checking for alGetError in -lopenal... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating src/Makefile
> config.status: executing depfiles commands
>

**Comment by scottwilson74** [comment]
I'm seeing the same on Linux x86_64.  I'm running Nobara Linux 43.  It's based on Fedora Linux 43.

**Comment by JosepMaJAZ** [comment]
I don't think v17 (current stable, but old version) will receive any fixes.
You should try building the dev branch.
